# Generated by Django 4.2.2 on 2023-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gerente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="GerenteAutomatico", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="email@gmail.com", max_length=254, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Gerentes",
            },
        ),
    ]
