# Generated by Django 4.2.4 on 2023-08-23 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oficinamebers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gerente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="gerente",
            name="nome",
        ),
        migrations.AddField(
            model_name="gerente",
            name="usuario",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
