# Generated by Django 4.2.5 on 2023-09-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oficinamebers", "0003_vendedor_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
    ]
