# Generated by Django 4.2.5 on 2023-09-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("oficinamebers", "0005_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="imagem",
        ),
        migrations.CreateModel(
            name="ImagensProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("principal", models.BooleanField(default=False)),
                (
                    "imagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="uploader.image"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imagens",
                        to="oficinamebers.produto",
                    ),
                ),
            ],
        ),
    ]
