# Generated by Django 4.2.5 on 2023-11-07 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oficinamebers", "0006_remove_produto_imagem_imagensproduto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gerente",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="vendedor",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Gerente",
        ),
        migrations.DeleteModel(
            name="Vendedor",
        ),
    ]
