# Generated by Django 4.2.5 on 2023-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oficinamebers", "0009_itenscompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscompra",
            name="preco_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
