# Generated by Django 4.2.5 on 2023-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oficinamebers", "0012_compra_tipo_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
