# Generated by Django 4.2.5 on 2023-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oficinamebers", "0014_alter_itenscompra_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
